
##
## ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██████╗  █████╗ ██████╗ ███████╗██████╗ 
## ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔══██╗██╔════╝██╔══██╗
## ███████║ ╚████╔╝ ██████╔╝██████╔╝██████╔╝███████║██████╔╝█████╗  ██████╔╝
## ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██╔═══╝ ██╔══██║██╔═══╝ ██╔══╝  ██╔══██╗
## ██║  ██║   ██║   ██║     ██║  ██║██║     ██║  ██║██║     ███████╗██║  ██║
## ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚══════╝╚═╝  ╚═╝
##

preload = ~/Pictures/Wallpaper/Kanagawa.png

wallpaper = ,~/Pictures/Wallpaper/Kanagawa.png

splash = false
